title: potter-theme
description: A Jekyll theme made by the awesome guy PoTTii for the CSZ Acadamy
baseurl: ""
url: https://csz-academy.github.io/potter-theme

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - potter-theme.gemspec
  - "_posts/README.md"
  - "_includes/README.md"
  - "_layouts/README.md"
  - "_sass/README.md"
  - "assets/README.md"
  - vendor
  - src
  - tailwind.config.js
  - potter.gemspec
  - README.md

plugins:
  - jekyll-feed

collections:
  members:
    output: true
