name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: "Test with Jekyll ${{ matrix.jekyll }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        jekyll: ["~> 3.9", "~> 4.2"]
    env:
      JEKYLL_VERSION: ${{ matrix.jekyll }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set Up Ruby 2.5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - run: npm ci

      - name: NPM Build
        run: |
          npm run build

      - name: Run tests
        run: |
          echo "TODO: There should be an example site to test the theme against - maybe CSZ Acadamy as a submodule?"
          exit 1
          bundle exec jekyll build

      - name: Build Gem
        run: gem build potter.gemspec

  deploy-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@main

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - run: npm ci

      - name: NPM Build
        run: |
          npm run build

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: ${{ runner.os }}-gems-

      - uses: helaili/jekyll-action@2.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pre_build_commands: "bundle update ffi"
