name: Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: "Test with Jekyll ${{ matrix.jekyll }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        jekyll: ["~> 3.9", "~> 4.2"]
    env:
      JEKYLL_VERSION: ${{ matrix.jekyll }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set Up Ruby 2.5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: Run tests
        run: |
          echo "TODO: There should be an example site to test the theme against - maybe CSZ Acadamy as a submodule?"
          exit 1
          bundle exec jekyll build
      - name: Build Gem
        run: gem build minima.gemspec
